-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 09:57:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Czytelnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Czytelnik` (
  `idCzytelnik` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Adres` VARCHAR(45) NULL,
  PRIMARY KEY (`idCzytelnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Książka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Książka` (
  `ISBN` VARCHAR(17) NOT NULL,
  `Tytuł` VARCHAR(45) NULL,
  `Wydawnictwo` VARCHAR(45) NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor_has_Książka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor_has_Książka` (
  `Autor_idAutor` INT NOT NULL,
  `Książka_ISBN` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`Autor_idAutor`, `Książka_ISBN`),
  INDEX `fk_Autor_has_Książka_Książka1_idx` (`Książka_ISBN` ASC) VISIBLE,
  INDEX `fk_Autor_has_Książka_Autor_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Książka_Autor`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Książka_Książka1`
    FOREIGN KEY (`Książka_ISBN`)
    REFERENCES `mydb`.`Książka` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Termin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Termin` (
  `idTermin` INT NOT NULL,
  `DluzejNiz2Tygodnie` TINYINT NULL,
  PRIMARY KEY (`idTermin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KartaWypozyczen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KartaWypozyczen` (
  `idKartaWypozyczen` INT NOT NULL,
  `KartaWypozyczencol` VARCHAR(45) NULL,
  `Książka_ISBN` VARCHAR(17) NOT NULL,
  `DataWypozyczenia` DATE NULL,
  `Czytelnik_idCzytelnik` INT NOT NULL,
  `Termin_idTermin` INT NOT NULL,
  PRIMARY KEY (`idKartaWypozyczen`),
  INDEX `fk_KartaWypozyczen_Książka1_idx` (`Książka_ISBN` ASC) VISIBLE,
  INDEX `fk_KartaWypozyczen_Czytelnik1_idx` (`Czytelnik_idCzytelnik` ASC) VISIBLE,
  INDEX `fk_KartaWypozyczen_Termin1_idx` (`Termin_idTermin` ASC) VISIBLE,
  CONSTRAINT `fk_KartaWypozyczen_Książka1`
    FOREIGN KEY (`Książka_ISBN`)
    REFERENCES `mydb`.`Książka` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KartaWypozyczen_Czytelnik1`
    FOREIGN KEY (`Czytelnik_idCzytelnik`)
    REFERENCES `mydb`.`Czytelnik` (`idCzytelnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KartaWypozyczen_Termin1`
    FOREIGN KEY (`Termin_idTermin`)
    REFERENCES `mydb`.`Termin` (`idTermin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
